-- =============================================
-- Migration: ingredients_master 테이블
-- Created: 2026-03-15
-- Description: 재료 마스터 데이터 (분류: SAFE_PLANT, EGG, DAIRY, ANIMAL, REVIEW)
-- =============================================

create table if not exists ingredients_master (
  id bigint generated always as identity primary key,
  name text not null,
  alias text,
  category text not null
    check (category in ('SAFE_PLANT', 'EGG', 'DAIRY', 'ANIMAL', 'REVIEW')),
  created_at timestamptz default now()
);

create unique index if not exists idx_ingredients_master_name
  on ingredients_master (name);

create index if not exists idx_ingredients_master_category
  on ingredients_master (category);

-- RLS
alter table ingredients_master enable row level security;

create policy "Anyone can read ingredients_master"
  on ingredients_master for select
  using (true);

create policy "Anyone can insert ingredients_master"
  on ingredients_master for insert
  with check (true);

-- =============================================
-- 데이터 삽입
-- =============================================

insert into ingredients_master (name, alias, category) values
-- === 감자/전분류 ===
('감자', null, 'SAFE_PLANT'),
('고구마', null, 'SAFE_PLANT'),
('감자전분', null, 'SAFE_PLANT'),
('고구마전분', null, 'SAFE_PLANT'),
('옥수수전분', null, 'SAFE_PLANT'),
('타피오카전분', null, 'SAFE_PLANT'),
-- === 가루류 ===
('강력분', null, 'SAFE_PLANT'),
('메밀가루', null, 'SAFE_PLANT'),
('밀가루', null, 'SAFE_PLANT'),
('박력분', null, 'SAFE_PLANT'),
('쌀가루', null, 'SAFE_PLANT'),
('옥수수가루', null, 'SAFE_PLANT'),
('중력분', null, 'SAFE_PLANT'),
-- === 곡물류 ===
('귀리', null, 'SAFE_PLANT'),
('메밀', null, 'SAFE_PLANT'),
('밀', null, 'SAFE_PLANT'),
('보리', null, 'SAFE_PLANT'),
('쌀', '멥쌀', 'SAFE_PLANT'),
('오트밀', '압착귀리', 'SAFE_PLANT'),
('옥수수', null, 'SAFE_PLANT'),
('찹쌀', null, 'SAFE_PLANT'),
('현미', null, 'SAFE_PLANT'),
-- === 떡/면류 ===
('가래떡', null, 'SAFE_PLANT'),
('떡국떡', null, 'SAFE_PLANT'),
('당면', '고구마당면', 'SAFE_PLANT'),
('라면사리', null, 'REVIEW'),
('소면', null, 'SAFE_PLANT'),
('쌀국수', null, 'SAFE_PLANT'),
('우동면', null, 'REVIEW'),
('칼국수면', null, 'REVIEW'),
-- === 콩/두부류 ===
('완두단백', null, 'SAFE_PLANT'),
('낫토', null, 'SAFE_PLANT'),
('청국장', null, 'SAFE_PLANT'),
('두부', null, 'SAFE_PLANT'),
('두유', null, 'SAFE_PLANT'),
('순두부', null, 'SAFE_PLANT'),
('유부', null, 'SAFE_PLANT'),
('콩비지', null, 'SAFE_PLANT'),
('강낭콩', null, 'SAFE_PLANT'),
('검은콩', null, 'SAFE_PLANT'),
('대두', null, 'SAFE_PLANT'),
('렌틸콩', null, 'SAFE_PLANT'),
('병아리콩', null, 'SAFE_PLANT'),
('완두콩', null, 'SAFE_PLANT'),
-- === 견과/씨앗류 ===
('땅콩', null, 'SAFE_PLANT'),
('아몬드', null, 'SAFE_PLANT'),
('잣', null, 'SAFE_PLANT'),
('캐슈넛', null, 'SAFE_PLANT'),
('호두', null, 'SAFE_PLANT'),
('들깨', null, 'SAFE_PLANT'),
('참깨', null, 'SAFE_PLANT'),
('해바라기씨', null, 'SAFE_PLANT'),
('호박씨', null, 'SAFE_PLANT'),
-- === 채소류 ===
('옥수수콘', null, 'SAFE_PLANT'),
('청양고추', null, 'SAFE_PLANT'),
('홍고추', null, 'SAFE_PLANT'),
('브로콜리', null, 'SAFE_PLANT'),
('콜리플라워', null, 'SAFE_PLANT'),
('냉이', null, 'SAFE_PLANT'),
('달래', null, 'SAFE_PLANT'),
('두릅', null, 'SAFE_PLANT'),
('당근', null, 'SAFE_PLANT'),
('도라지', null, 'SAFE_PLANT'),
('무', null, 'SAFE_PLANT'),
('연근', null, 'SAFE_PLANT'),
('열무', null, 'SAFE_PLANT'),
('우엉', null, 'SAFE_PLANT'),
('숙주', null, 'SAFE_PLANT'),
('콩나물', null, 'SAFE_PLANT'),
('가지', null, 'SAFE_PLANT'),
('단호박', null, 'SAFE_PLANT'),
('방울토마토', '체리토마토', 'SAFE_PLANT'),
('애호박', '호박', 'SAFE_PLANT'),
('오이', null, 'SAFE_PLANT'),
('토마토', null, 'SAFE_PLANT'),
('파프리카', null, 'SAFE_PLANT'),
('피망', null, 'SAFE_PLANT'),
('깻잎', null, 'SAFE_PLANT'),
('배추', null, 'SAFE_PLANT'),
('부추', null, 'SAFE_PLANT'),
('상추', null, 'SAFE_PLANT'),
('시금치', null, 'SAFE_PLANT'),
('알배추', null, 'SAFE_PLANT'),
('양배추', null, 'SAFE_PLANT'),
('양상추', null, 'SAFE_PLANT'),
('적양배추', null, 'SAFE_PLANT'),
('청경채', null, 'SAFE_PLANT'),
('케일', null, 'SAFE_PLANT'),
('셀러리', null, 'SAFE_PLANT'),
('아스파라거스', null, 'SAFE_PLANT'),
-- === 양념채소 ===
('대파', '파', 'SAFE_PLANT'),
('마늘', null, 'SAFE_PLANT'),
('생강', null, 'SAFE_PLANT'),
('양파', null, 'SAFE_PLANT'),
('쪽파', '실파', 'SAFE_PLANT'),
('미나리', null, 'SAFE_PLANT'),
-- === 버섯류 ===
('느타리버섯', null, 'SAFE_PLANT'),
('만가닥버섯', null, 'SAFE_PLANT'),
('목이버섯', null, 'SAFE_PLANT'),
('새송이버섯', null, 'SAFE_PLANT'),
('양송이버섯', null, 'SAFE_PLANT'),
('팽이버섯', null, 'SAFE_PLANT'),
('표고버섯', null, 'SAFE_PLANT'),
-- === 과일류 ===
('대추', null, 'SAFE_PLANT'),
('감', null, 'SAFE_PLANT'),
('귤', null, 'SAFE_PLANT'),
('딸기', null, 'SAFE_PLANT'),
('라임', null, 'SAFE_PLANT'),
('레몬', null, 'SAFE_PLANT'),
('바나나', null, 'SAFE_PLANT'),
('배', null, 'SAFE_PLANT'),
('블루베리', null, 'SAFE_PLANT'),
('사과', null, 'SAFE_PLANT'),
('오렌지', null, 'SAFE_PLANT'),
('포도', null, 'SAFE_PLANT'),
-- === 해조류 ===
('김', null, 'SAFE_PLANT'),
('다시마', null, 'SAFE_PLANT'),
('매생이', null, 'SAFE_PLANT'),
('미역', null, 'SAFE_PLANT'),
('톳', null, 'SAFE_PLANT'),
('파래', null, 'SAFE_PLANT'),
-- === 오일류 ===
('식용유', null, 'SAFE_PLANT'),
('올리브유', null, 'SAFE_PLANT'),
('카놀라유', null, 'SAFE_PLANT'),
('코코넛오일', null, 'SAFE_PLANT'),
('포도씨유', null, 'SAFE_PLANT'),
('들기름', null, 'SAFE_PLANT'),
('참기름', null, 'SAFE_PLANT'),
-- === 조미/양념류 ===
('소금', null, 'SAFE_PLANT'),
('레몬즙', null, 'SAFE_PLANT'),
('발사믹식초', null, 'SAFE_PLANT'),
('사과식초', null, 'SAFE_PLANT'),
('식초', null, 'SAFE_PLANT'),
('현미식초', null, 'SAFE_PLANT'),
('머스터드', null, 'SAFE_PLANT'),
('케첩', null, 'SAFE_PLANT'),
('토마토소스', null, 'SAFE_PLANT'),
('다시마육수', null, 'SAFE_PLANT'),
('버섯육수', null, 'SAFE_PLANT'),
('채소육수', null, 'SAFE_PLANT'),
('간장', null, 'SAFE_PLANT'),
('고추장', null, 'SAFE_PLANT'),
('국간장', null, 'SAFE_PLANT'),
('된장', null, 'SAFE_PLANT'),
('쌈장', null, 'SAFE_PLANT'),
('양조간장', null, 'SAFE_PLANT'),
('진간장', null, 'SAFE_PLANT'),
('고추기름', null, 'SAFE_PLANT'),
('고춧가루', null, 'SAFE_PLANT'),
('후추', null, 'SAFE_PLANT'),
-- === 감미료 ===
('꿀', null, 'REVIEW'),
('메이플시럽', null, 'SAFE_PLANT'),
('물엿', null, 'SAFE_PLANT'),
('설탕', null, 'SAFE_PLANT'),
('아가베시럽', null, 'SAFE_PLANT'),
('올리고당', null, 'SAFE_PLANT'),
('조청', null, 'SAFE_PLANT'),
('흑설탕', null, 'SAFE_PLANT'),
('알룰로스', null, 'SAFE_PLANT'),
-- === 달걀류 ===
('달걀', null, 'EGG'),
('달걀노른자', null, 'EGG'),
('달걀흰자', null, 'EGG'),
('메추리알', null, 'EGG'),
-- === 유제품 ===
('그릭요거트', null, 'DAIRY'),
('모짜렐라치즈', null, 'DAIRY'),
('버터', null, 'DAIRY'),
('분유', null, 'DAIRY'),
('생크림', null, 'DAIRY'),
('슈레드치즈', null, 'DAIRY'),
('연유', null, 'DAIRY'),
('요거트', null, 'DAIRY'),
('우유', null, 'DAIRY'),
('체다치즈', null, 'DAIRY'),
('크림치즈', null, 'DAIRY'),
('파마산치즈', null, 'DAIRY'),
-- === 동물성 ===
('젤라틴', null, 'ANIMAL'),
('건새우', null, 'ANIMAL'),
('새우', null, 'ANIMAL'),
('참치캔', null, 'ANIMAL'),
('갈치', null, 'ANIMAL'),
('고등어', null, 'ANIMAL'),
('멸치', null, 'ANIMAL'),
('명태', null, 'ANIMAL'),
('연어', null, 'ANIMAL'),
('문어', null, 'ANIMAL'),
('오징어', null, 'ANIMAL'),
('굴', null, 'ANIMAL'),
('바지락', null, 'ANIMAL'),
('조개', null, 'ANIMAL'),
('홍합', null, 'ANIMAL'),
('베이컨', null, 'ANIMAL'),
('소시지', null, 'ANIMAL'),
('햄', null, 'ANIMAL'),
('닭고기', null, 'ANIMAL'),
('돼지고기', null, 'ANIMAL'),
('소고기', null, 'ANIMAL'),
('오리고기', null, 'ANIMAL'),
('맛살', null, 'ANIMAL'),
('어묵', null, 'ANIMAL'),
('굴소스', null, 'ANIMAL'),
('액젓', null, 'ANIMAL'),
('참치액', null, 'ANIMAL'),
('멸치육수', null, 'ANIMAL'),
('사골육수', null, 'ANIMAL'),
('치킨스톡', null, 'ANIMAL'),
('새우젓', null, 'ANIMAL'),
-- === 확인 필요 ===
('카레블록', null, 'REVIEW'),
('라면스프', null, 'REVIEW'),
('우동다시', null, 'REVIEW'),
('만두피', null, 'REVIEW'),
('부침가루', null, 'REVIEW'),
('빵가루', null, 'REVIEW'),
('튀김가루', null, 'REVIEW'),
('식물성 대체육', null, 'REVIEW'),
('김치', null, 'REVIEW'),
('또띠아', null, 'REVIEW'),
('식빵', null, 'REVIEW'),
('카레가루', null, 'REVIEW'),
-- === 식물성 대체 ===
('코코넛밀크', null, 'SAFE_PLANT'),
('아몬드밀크', null, 'SAFE_PLANT'),
('오트밀크', null, 'SAFE_PLANT'),
('비건김치', null, 'SAFE_PLANT'),
('마요네즈', null, 'EGG'),
('비건마요', null, 'SAFE_PLANT')
on conflict (name) do nothing;
